import { Geist, Geist_Mono } from "next/font/google";
import '../Styles/style.css'
import Navbar from "./Components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next BLog ",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {



  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <Navbar />
          <main>{children}</main>
        </ClerkProvider>
      </body>
    </html>
  );
}
